### ISSUE TITLE
Typo in unsupported_platform_blackberry value in properties files

### ISSUE THREAD

**Issue by pdehaan** [mozilla/loop-client-l10n#4]
[/l10n/en_US/loop.properties:34](https://github.com/mozilla/loop-client-l10n/blob/2f0bbf9da17d3a0e7aeb3ad49515b989e4fe8c9f/l10n/en_US/loop.properties#L34) says "Blackberry", but if you're referring to the [smart phone manufacturer](http://us.blackberry.com/smartphones.html?lid=us:bb:devices&lpos=us:bb:devices) than it is actually "BlackBerry" (with an uppercase "B" in the middle). ([trademark](http://us.blackberry.com/legal/trademarks.html))

Probably need to tweak that in all the locales.

**Comment by Standard8** [comment]
a30631a460c98ab9f45eeef720db8ef2b303bf7e has now removed the BlackBerry string, so we're all good here.
